import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {ClerkProvider} from '@clerk/nextjs'
import {DocumentSelectionContextProvider} from "@/app/context/document-selection.context";
import {FileUploadingContext, FileUploadingContextProvider} from "@/app/context/file-uploading.context";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'ChatPDF',
	description: 'Generated by create next app',
}

export default function RootLayout({
	                                   children,
                                   }: {
	children: React.ReactNode
}) {
	return (
		<ClerkProvider>
			<FileUploadingContextProvider>
				<html lang="en">
				<DocumentSelectionContextProvider>
					<body className={inter.className}>{children}</body>
				</DocumentSelectionContextProvider>
				</html>
			</FileUploadingContextProvider>
		</ClerkProvider>
	)
}
