import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import {DocumentSelectionContextProvider} from "@/app/context/document-selection.context";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChatPDF',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
    <DocumentSelectionContextProvider>
	    <body className={inter.className}>{children}</body>
    </DocumentSelectionContextProvider>
    </html>       
    </ClerkProvider>
  )
}
